return --[[This list is autogenerated by build_default_list.py. If you wish to edit it, please make changes to the files in the list subdirectory.]] [[
ScaryAdjective
{
    "Scary",
    "Nightmarish",
    "Horrifying",
    "Chilling",
    "Horrendous",
    "Screaming",
}

ColorAdjective
{
    "Red",
    "Green",
    "Blue",
    "Yellow",
    "Purple",
    "Violet",
    "Orange",
    "White",
    "Black",
    "Gray",
    "Teal",
    "Cyan",
    "Magenta",
    "Lime",
    "Maroon",
    "Aqua",
    "Fuchsai",
    "Pink",
    "Olive",
    "Turquoise",
    "Gold",
    "Tan",
    "Ivory",
    "Steel",
    "Azure",
    "Indigo",
    "Lavender",
}


#Alphabetical Adjectives - Should generally sound like the letter they start with
A_Adjective
{
    "Attractive",
    "Awesome",
    "Angry",
    "Absolute",
    "Abyssal",
    "Abysmal",
    "Abandoned",
    "Aberrant",
    "Abrupt",
    "Absent",
    "Absurd",
    "Abnormal",
    "Academic",
    "Actual",
    "Acidic",
    "Adverse",
    "Admirable",
    "Adorable",
    "Affectionate",
    "African",
    "Affluent",
    "Aged",
    "Ageless",
    "Agreeable",
    "Airheaded",
    "Alabaster",
    "Alluring",
    "Alloyed",
    "Alien",
    "Aloof",
    "Ambiguous",
    "Amateur",
    "Antique",
    "Anxious",
    "Arcane",
    "Armless",
    "Armored",
    "American",
    "Artificial",
    "Apocalyptic",
    "Astute",
    "Astral",
    "Ashen",
    "Awful",
}

B_Adjective
{
    "Bad",
    "Baffled",
	"Bald",
    "Barmy",
    "Better",
    "Best",
    "Bitter",
    "Beautiful",
    "Black",
    "Blissful",
    "Bloody",
    "Blue",
    "Burnt",
    "Blunt",
    "Bloodthirsty",
    "Bold",
    "Brave",
    "Brilliant",
    "Brutal",
    "Bright",
    "Brazilian",
    "Busy",
    "Berserk",
    "Backward",
    "Batty",
    "Beefy",
    "Belgian",
    "Bent",
    "Biased",
    "Big",
    "Bionic",
    "Blameless",
    "Blind",
    "Blackened",
    "Buzzing",
}

C_Adjective
{
    "Callous",
    "Calm",
    "Cambrian",
    "Capable",
    "Captivating",
    "Caustic",
    "Casual",
    "Clumsy",
    "Corrupt",
    "Cool",
    "Cold",
    "Complex",
	"Creepy",
    "Chubby",
    "Clean",
    "Confused",
    "Courageous",
    "Covetous",
    "Coy",
    "Cuban",
    "Crazy",
    "Cruel",
    "Critical",
    "Cryptic",
    "Cranky",
    "Carnivorous",
}

D_Adjective
{
	"Daring",
    "Dangerous",
    "Delightful",
    "Dazzling",
    "Damaged",
    "Dank",
    "Dark",
    "Dazed",
    "Damned",
    "Deadlocked",
    "Dead",
    "Decisive",
    "Devout",
    "Detestable",
    "Despicable",
    "Depraved",
    "Deprived",
    "Devoted",
    "Deep",
    "Disturbed",
    "Disturbing",
    "Dishonest",
    "Dirty",
    "Diabolical",
    "Divine",
    "Dull",
    "Dreary",
    "Dodgy",
    "Dominating",
    "Diligent",
    "Drunk",
    "Dreadful",
    "Dumb",
    "Dutch",
    "Dynamic",
}

E_Adjective
{
    "Eager",
    "Easy",
    "Ecstatic",
    "Edgy",
    "Educated",
    "Efficient",
    "Egotistic",
	"Elegant",
    "Eerie",
    "Empowered",
    "Empty",
    "Eternal",
    "Ethereal",
    "Ethical",
    "Evasive",
    "Evil",
    "Extroverted",
    "Excited",
}

F_Adjective
{
	"Fat",
    "Fit",
    "Flabby",
    "Funny",
    "Ferocious",
    "Forgotten",
    "Fearless",
    "Fancy",
    "Faultless",
    "Flawless",
    "Flawed",
    "Flashy",
    "Festive",
    "Frightful",
    "Foul",
    "Foolish",
    "Frantic",
    "Fresh",
    "Frustrated",
    "Friendly",
    "Fussy",
    "Furious",
    "Filthy",
    "French",
    "Funky",
    "Formidable",
    "First",
}

G_Adjective
{
    "Gallant",
    "Gifted",
    "Glowing",
    "Gloomy",
    "Glum",
    "Good",
    "Graceful",
    "Grateful",
    "Gregarious",
    "Grouchy",
    "Grumpy",
    "Greedy",
    "Great",
	"Greasy",
    "Gorgeous",
    "Glamorous",
    "Gutsy",
    "Guiltless",
    "Guilty",
    "Glazed",
    "Gray",
    "Green",
    "Grisly",
    "Gutless",
    "Gilded",
    "Gold",
    "Golden",
}
H_Adjective
{
	"Handsome",
    "Happy",
    "Harsh",
    "Hateful",
    "Hated",
    "Hairy",
    "Heroic",
    "Heavenly",
    "Heavy",
    "Healthy",
    "Heinous",
    "Homeless",
    "Horrific",
    "Horrifying",
    "Hotheaded",
    "Hostile",
    "Hungry",
    "Humble",
    "Hardy",
    "Humorous",
    "Hellish",
    "Hexed",
    "Hispanic",
    "Hibernating",
    "Hideous",
    "Howling",
    "Hydrated",
}
I_Adjective
{
	"Incandescent",
    "Interesting",
    "Injured",
    "Idiotic",
    "Imaginative",
    "Illogical",
    "Impatient",
    "Important",
    "Impressionable",
    "Impure",
    "Impulsive",
    "Impossible",
    "Impractical",
    "Inactive",
    "Inconsiderate",
    "Indignant",
    "Indigo",
    "Intelligent",
    "Intense",
    "Involved",
    "Irish",
    "Irritating",
    "Infernal",
    "Innocent",
    "Inspiring",
    "Implike",
    "Impish",
    "Inane",
    "Invisible",
}

J_Adjective
{
    "Jealous",
    "Jittery",
	"Jovial",
    "Jazzy",
    "Jaded",
    "Jinxed",
    "Juvenile",
    "Japanese",
    "Joyful",
    "Jumpy",
    "Jurassic",
    "Jerky",
    "Judgmental",
    "Juicy",
}

K_Adjective
{
	"Keen",
    "Kind",
    "Kindred",
    "Kinetic",
    "Kingly",
    "Kooky",
    "Kenyan",
    "Korean",
}
L_Adjective
{
	"Long",
    "Late",
    "Lethargic",
    "Liberal",
    "Light",
    "Loathsome",
    "Lively",
    "Likeable",
    "Lackluster",
    "Lustrous",
    "Lithe",
    "Languid",
    "Lanky",
    "Lacerated",
    "Loyal",
    "Lovely",
    "Logical",
    "Large",
    "Livid",
    "Loose",
    "Lauging",
}

M_Adjective
{
	"Machiavellian",
    "Mad",
    "Magical",
    "Magestic",
    "Magnificent",
    "Maroon",
    "Mature",
    "Maternal",
    "Manipulative",
    "Mean",
    "Mediocre",
    "Memorable",
    "Mercurial",
    "Merry",
    "Mexican",
    "Meticulous",
    "Mirthful",
    "Miserable",
    "Modern",
    "Modest",
    "Muddy",
    "Musical",
    "Motivated",
    "Mortifying",
    "Mortified",
    "Mysterious",
}

N_Adjective
{
	"Naked",
    "Naughty",
    "Naive",
    "Natural",
    "Nasty",
    "Neat",
    "Negative",
    "Nervous",
    "Nice",
    "Noble",
    "Normal",
    "Nosy",
    "Numb",
    "Nutty",
    "Native",
    "Nigerian",
    "Noxious",
    "Ninth",
    "Neural",
    "Necromantic",
}

O_Adjective
{
	"Oafish",
    "Obedient",
    "Obscene",
    "Obnoxious",
    "Odd",
    "Offensive",
    "Okay",
    "Optimistic",
    "Outraged",
    "Outgoing",
    "Orange",
    "Outspoken",
    "Outstanding",
    "Overwhelming",
    "Old",
    "Ordinary",
    "Overweight",
    "Obtuse",
    "Occult",
    "Obscure",
    "Oily",
    "Oiled",
    "Olive",
    "Omnivorous",
}

P_Adjective
{
    "Painted",
    "Panicked",
    "Passive",
    "Patient",
    "Patronizing",
    "Peaceful",
    "Peckish",
    "Perfect",
    "Perpetual",
    "Petite",
    "Persistent",
    "Perforated",
    "Pleasant",
    "Pitiful",
    "Poor",
    "Polite",
    "Practical",
    "Precise",
    "Precious",
    "Proud",
    "Pristine",
    "Pure",
    "Prejudiced",
    "Presumptuous",
}

Q_Adjective
{
    "Queasy",
    "Quiet",
    "Quirky",
    "Quick",
    "Quaint",
    "Quotable",
    "Queenly",
    "Quadratic",
    "Questionable",
    "Quarantined",
}

R_Adjective
{
    "Radiant",
    "Radical",
    "Rash",
    "Rational",
    "Rattled",
    "Ready",
    "Real",
    "Red",
    "Remarkable",
    "Restrained",
    "Religious",
    "Relaxed",
    "Rightwing",
    "Rude",
    "Righteous",
    "Rich",
    "Rigid",
    "Remorseful",
    "Remorseless",
    "Respectable",
    "Ruthless",
    "Ridiculous",
    "Rare",
    "Raw",
    "Rosy",
    "Rusty",
    "Russian",
}
S_Adjective
{
	"Sad",
    "Sadistic",
    "Savage",
    "Saucy",
    "Scary",
    "Scarred",
    "Scornful",
    "Selfish",
    "Senile",
    "Seductive",
    "Serene",
    "Serious",
    "Sickening",
    "Shiny",
    "Shivering",
    "Shy",
    "Sixth",
    "Small",
    "Snarky",
    "Soulless",
    "Soulful",
    "Sour",
    "Soft",
    "Sweet",
    "Swollen",
}

T_Adjective
{
	"Tactful",
    "Talented",
    "Tall",
    "Teal",
    "Terrifying",
    "Terrified",
    "Terrible",
    "Tricky",
    "Thin",
    "Tiny",
    "Twinkling",
    "Treasured",
    "Tough",
    #"Thirsty",
    #"Thoughtless",
    #"Thankless",
    #"Thankful",
    "Traditional",
    "Turbulent",
    "Teenage",
    "Terrific",
    "Tight",
}

U_Adjective
{
	"Ugandan",
    "Ultimate",
    "Ultra",
    "Ultrasonic",
    "Ultraviolet",
    "Uptight",
    "Underage",
    "Unashamed",
}

V_Adjective
{
	"Vague",
    "Valiant",
    "Vain",
    "Vehement",
    "Vengeful",
    "Verbose",
    "Vexed",
    "Vexing",
    "Vigilant",
    "Vile",
    "Villainous",
    "Vicious",
    "Vivacious",
    "Voracious",
    "Volcanic",
    "Vulgar",
    "Vibrant",
}

W_Adjective
{
	"Wacky",
    "Wanted",
    "Warring",
    "Warped",
    "Woke",
    "Wishful",
    "Witty",
    "Wily",
    "Wonderful",
    "White",
    "Wicked",
    "Wingless",
    "Wispy",
    "Winded",
    "Wheezing",
    "Weary",
    "Weeping",

}

X_Adjective
{
    "Xenophobic",
    "Xenocidal",
}

Y_Adjective
{
	"Yellow",
    "Yawning",
    "Yankee",
    "Young",
    "Youthful",
    "Yummy",
    "Yielding",
    "Yonder",
}

Z_Adjective
{
	"Zealous",
    "Zany",
    "Zesty",
}
AnimalNoun
{
    [%1] "{A_AnimalNoun}",
    [%1] "{B_AnimalNoun}",
    [%1] "{C_AnimalNoun}",
    [%1] "{D_AnimalNoun}",
    [%1] "{E_AnimalNoun}",
    [%1] "{F_AnimalNoun}",
    [%1] "{G_AnimalNoun}",
    [%1] "{H_AnimalNoun}",
    [%1] "{I_AnimalNoun}",
    [%1] "{J_AnimalNoun}",
    [%1] "{K_AnimalNoun}",
    [%1] "{L_AnimalNoun}",
    [%1] "{M_AnimalNoun}",
    [%1] "{N_AnimalNoun}",
    [%1] "{O_AnimalNoun}",
    [%1] "{P_AnimalNoun}",
    [%1] "{R_AnimalNoun}",
    [%1] "{S_AnimalNoun}",
    [%1] "{T_AnimalNoun}",
    [%1] "{V_AnimalNoun}",
    [%1] "{W_AnimalNoun}",
}

A_AnimalNoun
{
    "Aardvark",
    "Albatross",
    "Alligator",
    "Anaconda",
    "Anglerfish",
    "Ant",
    "Antelope",
    "Antlion",
    "Ape",
    "Armadillo",
}

B_AnimalNoun
{
    "Baboon",
    "Badger",
    "Barnacle",
    "Barracuda",
    "Basilisk",
    "Bass",
    "Bat",
    "Bear",
    "Beaver",
    "Bedbug",
    "Bee",
    "Beetle",
    "Bird",
    "Bison",
    "Blackbird",
    "Boa",
    "Boar",
    "Bobcat",
    "Buffalo",
    "Buffalo",
    "Bug",
    "Bull",
    "Bunny",
    "Butterfly",
    "Buzzard",
}

C_AnimalNoun
{
    "Camel",
    "Capybara",
    "Cardinal",
    "Caribou",
    "Carp",
    "Cat",
    "Catshark",
    "Caterpillar",
    "Catfish",
    "Centipede",
    "Cephalopod",
    "Chameleon",
    "Cheetah",
    "Chickadee",
    "Chicken",
    "Chimp",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Cicada",
    "Clam",
    "Clownfish",
    "Cobra",
    "Cockroach",
    "Condor",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crawdad",
    "Crayfish",
    "Cricket",
    "Crocodile",
    "Crow",
}

D_AnimalNoun
{
    "Deer",
    "Dinosaur",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dove",
    "Dragonfly",
    "Dragon",
    "Duck",
}

E_AnimalNoun
{
    "Eagle",
    "Earthworm",
    "Earwig",
    "Echidna",
    "Eel",
    "Elephant",
    "Elk",
}

F_AnimalNoun
{
    "Falcon",
    "Ferret",
    "Finch",
    "Firefly",
    "Fish",
    "Flamingo",
    "Flea",
    "Fly",
    "Fox",
    "Frog",
}

G_AnimalNoun
{
    "Gazelle",
    "Gecko",
    "Gerbil",
    "Giant",
    "Giraffe",
    "Goat",
    "Goldfish",
    "Goose",
    "Gopher",
    "Gorilla",
    "Grasshopper",
    "Grizzly",
    "Grue",
    "Guinea Pig",
    "Gull",
    "Guppy",
}

H_AnimalNoun
{
    "Hammerhead",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippo",
    "Hookworm",
    "Hornet",
    "Horse",
    "Human",
    "Hummingbird",
    "Hyena",
}

I_AnimalNoun
{
    "Iguana",
    "Imp",
    "Insect",
}

J_AnimalNoun
{
    "Jackal",
    "Jaguar",
    "Jellyfish",
}

K_AnimalNoun
{
    "Kangaroo",
    "Koala",
    "Koi",
    "Krill",
}

L_AnimalNoun
{
    "Ladybug",
    "Lamprey",
    "Leech",
    "Lemming",
    "Lemur",
    "Leopard",
    "Lion",
    "Lizard",
    "Llama",
    "Lobster",
}

M_AnimalNoun
{
    "Mackerel",
    "Magpie",
    "Mallard",
    "Manatee",
    "Mandrill",
    "Manta Ray",
    "Mantis",
    "Mastodon",
    "Meerkat",
    "Mink",
    "Minnow",
    "Mockingbird",
    "Mole",
    "Mollusk",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Moth",
    "Mouse",
    "Mule",
}

N_AnimalNoun
{
    "Narwhal",
    "Needlefish",
    "Newt",
    "Nighthawk",
    "Nightingale",
    "Numbat",
}

O_AnimalNoun
{
    "Ocelot",
    "Octopus",
    "Orangutan",
    "Orca",
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
}

P_AnimalNoun
{
    "Panda",
    "Panther",
    "Parakeet",
    "Parrot",
    "Peacock",
    "Pelican",
    "Penguin",
    "Pig",
    "Pigeon",
    "Piranha",
    "Platypus",
    "Polar Bear",
    "Pony",
    "Porcupine",
    "Possum",
    "Primate",
    "Puma",
    "Python",
}
R_AnimalNoun
{
    "Rabbit",
    "Raccoon",
    "Rat",
    "Rattlesnake",
    "Raven",
    "Reindeer",
    "Reptile",
    "Rhinoceros",
    "Roadrunner",
    "Rodent",
    "Rooster",
    "Roundworm",
}

S_AnimalNoun
{
    "Salamander",
    "Salmon",
    "Scorpion",
    "Seahorse",
    "Shark",
    "Sheep",
    "Shrew",
    "Shrimp",
    "Silkworm",
    "Silverfish",
    "Skunk",
    "Sloth",
    "Slug",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Squid",
    "Squirrel",
    "Starfish",
    "Stingray",
    "Stork",
    "Swallow",
    "Swan",
    "Swordfish",
}

T_AnimalNoun
{
    "Tarantula",
    "Termite",
    "Tick",
    "Tiger",
    "Toad",
    "Tortoise",
    "Toucan",
    "Trout",
    "Tuna",
    "Turkey",
    "Turtle",
    "Tyrannosaurus",
}

V_AnimalNoun
{
    "Viper",
    "Vixen",
    "Vulture",
}

W_AnimalNoun
{
    "Walrus",
    "Wasp",
    "Weasel",
    "Whale",
    "Wildcat",
    "Wildebeest",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodchuck",
    "Woodpecker",
    "Worm",
}
ArtilleryTurretName
{
    "{ArtilleryDivine1} {ArtilleryDivine2}",
    "{OffspringNoun} of {Deity}", 
    "{DivineBeing}'s {DivineBeingNoun}",
}

#These two are meant to work with eachother for occasional artillery names
ArtilleryDivine1
{
    "Hell",
    "God",
    "Angel",
    "Devil",
    "Demon",
    "Nephilim",
    "Dawn",
    "Life",
    "World",
    "Heaven",
    "Sky",
    "Peace", #Maybe?
}

ArtilleryDivine2
{
    "Breaker",
    "Cracker",
    "Splitter",
    "Destroyer",
    "Hammer",
    "Crusher",
    "Eraser",
    "Spear",
    "Javelin",
    "Deliverer",
    "Cannon",
    "Weapon",
    "Child",
}

OffspringNoun
{
    "Child",
    "Son",
    "Daughter",
    "Progeny",
    "Descendant",
}

Deity
{
    "God",
    "Satan",
    "Lucifer",
    "Ares",
    "Athena",
    "Eris",
    "Gaia",
    "Zeus",
    "Hades",
    "Earth",
    "Mars",
    "Venus",
    "Neptune",
    "Osiris",
    "Ra",
    "Thor",
    "Heaven",
    "Hell",
}


DivineBeing
{
    "God",
    "Devil",
    "Demon",
    "Angel",
    "The Lord",
}

DivineBeingNoun
{
    "Forgiveness",
    "Sadness",
    "Anger",
    "Apathy",
    "Pity",
    "Envy",
    "Hatred",
    "Disdain",
    "Love",
    "Solution",
    "Gift",
    "Messenger",
    "Machine",
    "Device",
    "Solution",
}

CountryNoun
{
    "America",
    "Freedomland",
    "Gunland",
    "Gunistan",
    "Guntopia",
    "Africa",
    "Chicago",
    "Detroit",
    "Britain",
    "Australia",
    "Kangarooland",
    "Russia",
    "China",
    "Japan",
}

CountryAdjective
{
    "American",
    "Gunlandian",
    "Gunistanian",
    "African",
    "British",
    "Australian",
    "Russian",
    "Chinese",
    "Japanese",
}

DeathNoun
{
    "Death",
    "Extinction",
    "Genocide",
    "Erasure",
}

KillerNoun
{
    "Killer",
    "Murderer",
    "Exterminator",
    "Executioner",
    "Butcher",
    "Slayer",
    "Soldier",
    "Assassin",
    "Eraser",
    "Ender",
    "Deathbringer",
    "Death Dealer",
}




#███████╗██╗      █████╗ ███╗   ███╗███████╗                 
#██╔════╝██║     ██╔══██╗████╗ ████║██╔════╝                 
#█████╗  ██║     ███████║██╔████╔██║█████╗                   
#██╔══╝  ██║     ██╔══██║██║╚██╔╝██║██╔══╝                   
#██║     ███████╗██║  ██║██║ ╚═╝ ██║███████╗                 
#╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝                 
#                                                            
#████████╗██╗  ██╗██████╗  ██████╗ ██╗    ██╗███████╗██████╗ 
#╚══██╔══╝██║  ██║██╔══██╗██╔═══██╗██║    ██║██╔════╝██╔══██╗
#   ██║   ███████║██████╔╝██║   ██║██║ █╗ ██║█████╗  ██████╔╝
#   ██║   ██╔══██║██╔══██╗██║   ██║██║███╗██║██╔══╝  ██╔══██╗
#   ██║   ██║  ██║██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║
#   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝

#Flamethrower Turret Name
FlamethrowerTurretName
{
    "{FlamethrowerTurretAdjective} {AlienNoun} {FlamethrowerTurretNoun}",
    "{FlamethrowerTurretAdjective} {CountryAdjective} {FlamethrowerTurretNoun}",
    "{AlienNoun} {FireNoun}",
}

FlamethrowerTurretAdjective
{
    "{FireAdjective}",
    "{GloryAdjective}",
}

FlamethrowerTurretNoun
{
    "{FireNoun}",
    "{KillerNoun}",
    "{WeaponPersonNoun}",
}

#Intended for flamethrower turret
FireAdjective
{
    "Hot",
    "Spicy",
    "Spiced",
    "Habanero",
    "Burning",
    "Toasty",
    "Toasted",
    "Warm",
    "Blazing",
    "Heated",
    "Sweltering",
    "Sizzling",
    "Scorching",
    "Scorched",
    "Broiling",
    "Broiled",
    "Roasting",
    "Roasted",
    "Igneous",
    "Smoking",
    "Smoked",
    "Smoldering",
    "Blistering",
    "Fiery",
    "Sunny",
    "Glowing",
    "Boiling",
    "Incendiary",
    "Molten",
}

FireNoun
{
    "Oven",
    "Furnace",
    "Bonfire",
    "Microwave",
    "Cauldron",
    "Crucible",
    "Pyre",
    "Torch",
    "Pyro",
    "Roaster",
    "Scorcher",
    "Melter",
    "Burner",
}


GamertagName
{
    "{MlgOuter}",
}

MlgOuter
{
    [3]"{MlgInner}",
    "-={MlgInner}=-",
    "xX{MlgInner}Xx",
    "XxX{MlgInner}XxX",
    ".:{MlgInner}:.",
    ".::{MlgInner}::.",
}

MlgInner
{
    "{GT_CoreName}{GT_RandomNumber}",
}

GT_CoreName
{
    "{GT_PowerfulBeing}{GT_Joiner}{GT_Slayer}",
    "{GT_CoolWord}{GT_Joiner}{GT_Slayer}",
    "{ColorAdjective}{GT_Joiner}{GT_CoolWord}",
    "{AnimalAlliterationName}",
}

GT_Joiner
{
    [2]"",
    "-",
    "_",
}

GT_CoolWord
{
    "Light",
    "Plasma",
    "Shadow",
    "Shade",
    "Darkness",
    "Scar",
    "Oblivion",
    "Steel",
    "Storm",
    "Void",
    "Vortex",
    "Dragon",
    "Demon",
    "Zombie",
    "Chaos",
}

GT_PowerfulBeing
{
    "Angel",
    "Demon",
    "God",
    "Galaxy",
    "Heaven",
    "World",
}

GT_Slayer
{
    "Slayer",
    "Killer",
    "Destroyer",
    "Reaper",
}

GT_RandomNumber
{
    [10]"",
    [3]"420",
    [3]"1337",
    [3]"666",
    [3]"0",
    "1",
    [2]"2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "20",
    "30",
    [0.5]"90",
    [0.5]"91",
    [0.5]"92",
    [0.5]"93",
    [0.5]"94",
    [0.5]"95",
    [0.5]"96",
    [0.5]"97",
    [0.5]"98",
    [0.5]"99",
    "00",
    "777",
}




AnimalAlliterationName
{
    "{A_Adjective} {A_AnimalNoun}",
    "{B_Adjective} {B_AnimalNoun}",
    "{C_Adjective} {C_AnimalNoun}",
    "{D_Adjective} {D_AnimalNoun}",
    "{E_Adjective} {E_AnimalNoun}",
    "{F_Adjective} {F_AnimalNoun}",
    "{G_Adjective} {G_AnimalNoun}",
    "{H_Adjective} {H_AnimalNoun}",
    "{I_Adjective} {I_AnimalNoun}",
    "{J_Adjective} {J_AnimalNoun}",
    "{K_Adjective} {K_AnimalNoun}",
    "{L_Adjective} {L_AnimalNoun}",
    "{M_Adjective} {M_AnimalNoun}",
    "{N_Adjective} {N_AnimalNoun}",
    "{O_Adjective} {O_AnimalNoun}",
    "{P_Adjective} {P_AnimalNoun}",
    #"{Q_Adjective} {Q_AnimalNoun}",
    "{R_Adjective} {R_AnimalNoun}",
    "{S_Adjective} {S_AnimalNoun}",
    "{T_Adjective} {T_AnimalNoun}",
    #"{U_Adjective} {U_AnimalNoun}",
    "{V_Adjective} {V_AnimalNoun}",
    "{W_Adjective} {W_AnimalNoun}",
    #"{X_Adjective} {X_AnimalNoun}",
    #"{Y_Adjective} {Y_AnimalNoun}",
    #"{Z_Adjective} {Z_AnimalNoun}",
}

GenericTurretName
{
    "{AnimalAlliterationName}",
}
GloryAdjective
{
    "Glorious",
    "Dignified",
    "Majestic",
    "Celebritory",
    "Triumphant",
    "Immortal",
    "Splendid",
    "Great",
    "Prestigious",
    "Honored",
    "Honorable",
    "Grandiose",
    "Grand",
    "Courageous",
    "Brave",
    "Exalted",
    "Illustrious",
    "Renowned",
    "Magnificent",
    "Eminent",
    "Sublime",
}

GloryNoun
{
    "Glory",
    "Dignity",
    "Majesty",
    "Celebrity",
    "Triumph",
    "Immortality",
    "Splendor",
    "Greatness",
    "Prestige",
    "Honor",
    "Grandeur",
    "Kudos",
    "Courage",
    "Bravery",
    "Exaltation",
    "Illustriousness",
    "Renown",
    "Magnificence",
    "Eminence",
    "Sublimity",
    "Justice",
}
#Gun Turret Name
GunTurretName
{
    "{GloryAdjective} {AlienNoun} {KillerNoun}",
    "{AlienNoun} {KillerNoun}",
    "{OffspringNoun} of {GloryNoun}",
    "{SearcherNoun} of {GloryNoun}",
    "{GloryNoun} {SearcherNoun}",
    "{TurretBarrelNoun} of {PainNoun}",
    "{TurretBarrelNoun} of {DeathNoun}",
    "{BattleNoun} {WeaponPersonNoun}",
    "{CountryAdjective} {BattleNoun} {WeaponPersonNoun}",
    "{CountryAdjective} {LiberatorNoun}",
    "{GloryAdjective} {WeaponPersonNoun}",
    "{GloryAdjective} {BattleNoun} {WeaponPersonNoun}",
}

RotatingAdjective
{
    "Spinning",
    "Revolving",
    "Spiraling",
    "Gyrating",
    "Turning",
    "Rotating",
    "Whirling",
    "Reeling",
}

GunBarrelsNoun
{
    "Barrels",
    "Drums",
    "Cylinders",
}

TurretBarrelNoun
{
    "Six {GloryAdjective} {GunBarrelsNoun}",
    "Six {RotatingAdjective} {GunBarrelsNoun}",
    "Six {ScaryAdjective} {GunBarrelsNoun}",
}

PainNoun
{
    "Pain",
    "Agony",
    "Suffering",
    "Torture",
    "Torment",
}



SearcherNoun
{
    "Seeker",
    "Aspirant",
}

LiberatorNoun
{
    "Liberator",
    "Deliverer",
    "Rescuer",
    "Redeemer",
}

#Generic alien terms to throw into names
AlienNoun
{
    "Bug",
    "Alien",
    "Biter",
    "Spitter",
    "Worm",
    "Ankle Biter",
    "Vermin",
    "Pest",
    "Insect",
    "Arachnid",
    "Gnat",
    "Grub",
    "Beetle",
    "Cricket",
}


FullSoldierNoun
{
}

BattleNoun
{
    "War",
    "Battle",
    "Freedom",
    "Liberation",
}

WeaponPersonNoun
{
    "Commander",
    "Leader",
    "Chief",
    "Hero",
    "Veteran",
    "Soldier",
    "Sergeant",
    "Colonel",
    "Lieutenant",
}

]]